# Generated by Django 5.2 on 2025-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
